// Auto-generated by Specwright — edit or regenerate via the UI
export default [
  {
    moduleName: '@TodoWorkflow',
    category: '@Workflows',
    subModuleName: ['@0-Precondition', '@1-VerifyInList'],
    fileName: 'todo_workflow',
    pageURL: 'http://localhost:5174/todos/new',
    inputs: {},
    instructions: [
      '@0-Precondition (precondition @cross-feature-data): Navigate to /todos/new. Fill Title with <gen_test_data>. Set Priority to High using the MUI Select dropdown. Type "Work" in Category Autocomplete and select it. Click Create Todo. Verify success snackbar appears. Capture the todo title and save as predata under scope "todoworkflow". Also snapshot the todo-app-todos localStorage key.',
      '@1-VerifyInList (workflow-consumer): Load predata from "todoworkflow". Navigate to /todos. Verify the created todo appears in the list with the correct title from predata. Verify the Priority chip shows "High".',
      '@1-VerifyInList (workflow-consumer): Load predata from "todoworkflow". Navigate to /todos. Click the complete checkbox on the created todo — verify it is checked. Switch to Completed filter tab — verify the todo appears there.',
      '@1-VerifyInList (workflow-consumer): Load predata from "todoworkflow". Navigate to /todos. Click the delete button on the created todo — verify a MUI confirmation dialog appears. Click Confirm — verify the todo is removed from the list.',
    ],
    explore: true,
    runExploredCases: false,
    runGeneratedCases: false,
  }
];
