// Auto-generated by Specwright — edit or regenerate via the UI
export default [
  {
    moduleName: '@ListWorkflow',
    category: '@Workflows',
    subModuleName: ['@0-CreateList', '@1-AddShows', '@2-VerifyList'],
    fileName: 'list_workflow',
    pageURL: 'https://specwright-show-buff.vercel.app/lists',
    filePath: 'e2e-tests/data/migrations/files/list_workflow.xlsx',
    inputs: {},
    instructions: [
      'Just process the attached test file instructions',
    ],
    explore: true,
    runExploredCases: false,
    runGeneratedCases: false,
  }
];
