// Auto-generated by Specwright — edit or regenerate via the UI
export default [
  {
    moduleName: '@FavoritesWorkflow',
    category: '@Workflows',
    subModuleName: ['@0-Precondition', '@1-VerifyFavorites'],
    fileName: 'favorites_workflow',
    pageURL: 'https://specwright-show-buff.vercel.app/home',
    inputs: {},
    instructions: [
      '@0-Precondition: Navigate to home page, click on a show card to open detail page, note the show name, click Add to Favorites, verify confirmation that show is added',
      '@1-VerifyFavorites: Navigate to /favorites page, verify the show from the precondition appears in the favorites grid with correct title, verify favorites count badge matches',
    ],
    explore: true,
    runExploredCases: false,
    runGeneratedCases: false,
  }
];
