// Auto-generated by Specwright — edit or regenerate via the UI
export default [
  {
    moduleName: '@ListWorkflow',
    category: '@Workflows',
    subModuleName: ['@0-CreateList', '@1-AddShows', '@2-VerifyList'],
    fileName: 'list_workflow',
    pageURL: 'https://specwright-show-buff.vercel.app/lists',
    filePath: 'e2e-tests/data/migrations/files/list_workflow.xlsx',
    instructions: [
      '@0-CreateList: Navigate to /lists, create a new list named "My Top Shows", verify the list card appears and clicking it goes to the list detail page',
      '@1-AddShows: Navigate to home page, click a show, use the Add to List dropdown to add it to "My Top Shows", go to a second show and also add it to "My Top Shows"',
      '@2-VerifyList: Navigate to /lists, click "My Top Shows" list card, verify both shows appear in the grid, verify the show count badge on the list card shows 2',
    ],
    explore: true,
    runExploredCases: false,
    runGeneratedCases: false,
  }
];
